services:
  fusion:
    build:
      target: fusiond
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    volumes:
      - ~/.fusiond:/root/.fusiond
    ports:
      - "27657:27657"
      - "9790:9790"
      - "1717:1717"
    environment:
      FUSIOND_API_ENABLE: "true"
      FUSIOND_API_ADDRESS: "tcp://0.0.0.0:1717"
      FUSIOND_API_ENABLED_UNSAFE_CORS: "true"
      FUSIOND_GRPC_ADDRESS: "0.0.0.0:9790"
      FUSIOND_RPC_LADDR: "tcp://0.0.0.0:27657"

  faucet:
    build:
      target: faucet
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    ports:
      - "8000:8000"
    environment:
      NODE: http://fusion:27657
      MNEMONIC: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"

  relayer-eth:
    build:
      target: relayer-eth
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    environment:
      ETH_URL: $ETH_URL
      FUSION_URL: fusion:9790
      WALLET_TYPE: ETH_SEPOLIA
      CHAIN_ID: 11155111

  mokr:
    build:
      target: mokr
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    environment:
      FUSION_URL: fusion:9790
      MNEMONIC: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"

  web:
    build:
      target: web
      args:
        FAUCET_URL: "http://127.0.0.1:8000"
        FUSION_RPC_URL: "http://127.0.0.1:27657"
        FUSION_REST_URL: "http://127.0.0.1:1717"
    ports:
      - "3000:80"
