port: 8080
path: db
loglevel: debug
logformat: plain
logtofile: false
keyring_addr: "qredokeyring1ph63us46lyw56vrzgaq"
chain_id: "qredofusiontestnet_257-1"
fusion_url: localhost:9090
mnemonic: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"
mpc:
  mock: true
  node:
    - host: localhost
      port: 8000