version: '3.7'

services:

  fusion:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: fusiond
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    volumes:
      - ~/.fusiond:/root/.fusiond
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"
    environment:
      FUSIOND_API_ENABLE: "true"
      FUSIOND_API_ADDRESS: "tcp://0.0.0.0:1317"
      FUSIOND_API_ENABLED_UNSAFE_CORS: "true"
      FUSIOND_GRPC_ADDRESS: "0.0.0.0:9090"
      FUSIOND_RPC_LADDR: "tcp://0.0.0.0:26657"

  faucet:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: faucet
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    ports:
      - "8000:8000"
    environment:
      NODE: http://fusion:26657
      MNEMONIC: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"

  relayer-eth:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: relayer-eth
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    environment:
      ETH_URL: $ETH_URL
      FUSION_URL: fusion:9090
      WALLET_TYPE: ETH_SEPOLIA
      CHAIN_ID: 11155111

  mokr:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: mokr
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    environment:
      FUSION_URL: fusion:9090
      MNEMONIC: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"

  mpc-relayer:
    image: mpc-relayer:latest
    container_name: "mpc-relayer"
    hostname: mpc-relayer
    volumes:
      - "./config-mpc-relayer.yml:/config.yml"
      - "./db:/db"
    user: "1000"
    command: --config /config.yml
    ports:
      - "8080:8080"

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: web
      args:
        FAUCET_URL: "http://127.0.0.1:8000"
        FUSION_RPC_URL: "http://127.0.0.1:26657"
        FUSION_REST_URL: "http://127.0.0.1:1317"
        BLACKBIRD_API_URL: "http://fs-blackbird-ui.dev.development-qredo.com"
    ports:
      - "3000:80"
