port: 8080
path: db
loglevel: debug
logformat: plain
logtofile: false
keyring_id: "0"
fusion_url: 127.0.0.1:26657
mnemonic: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"