name: test-blockchain
on:
  push:
    branches:
      - master
    paths:
      - blockchain/**
  pull_request:
    paths:
      - blockchain/**

env:
  GOPRIVATE: gitlab.qredo.com,github.com/qredo

permissions:
  contents: read

jobs:
  unit-test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blockchain
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: "**/*.sum"
      - run: git config --global url."https://${{ secrets.PAT_GITHUB }}@github.com".insteadOf "https://github.com"
      - name: Build
        run: go build -v ./cmd/...
      - name: Test
        run: make test
